openapi: 3.0.1..
info:
  title: aor1cep
  description: ""
  version: 1.0.0
servers:
- url: https://localhost:8080/aor1cep
- url: http://localhost:8080/aor1cep
paths:
  /aor1Cep/Con/{cepCode}:
    get:
      tags:
      - aor1cep
      operationId: getAor1CepSerCon
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: cepCode
        in: path
        required: true
        schema:
          maxLength: 8
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAor1CepSerCon_response_200'
components:
  schemas:
    getAor1CepSerCon_response_200:
      type: object
      properties:
        LK_CEP:
          type: object
          properties:
            LK_CEPCODE:
              maxLength: 8
              type: string
            LK_UF:
              maxLength: 2
              type: string
            LK_CIDADE:
              maxLength: 30
              type: string
            LK_BAIRRO:
              maxLength: 30
              type: string
            LK_LOGRADOURO:
              maxLength: 30
              type: string
